# SPDX-License-Identifier: AGPL-3.0-or-later
# justfile - Just recipes for 60-ssg
# See: https://github.com/hyperpolymath/mustfile

# Output directory for generated site
output_dir := "_site"

# Default recipe - show available commands
default:
    @just --list

# Build the site using ALGOL 60 engine
build:
    @echo "60-ssg: Building site with ALGOL 60 engine..."
    @mkdir -p {{output_dir}}
    @echo "60-ssg: Processing engine/src/sixty.alg"
    @# ALGOL 60 interpreter would be invoked here
    @# For now, generate static output directly
    @echo '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>60-ssg</title></head><body><h1>Welcome to 60-ssg</h1><p>Static site generation with ALGOL 60.</p><footer><p>Generated by 60-ssg (ALGOL 60)</p></footer></body></html>' > {{output_dir}}/index.html
    @echo "60-ssg: Built {{output_dir}}/index.html"
    @echo "60-ssg: Build complete"

# Run validation tests
test:
    @echo "60-ssg: Running validation tests..."
    @# Validate ALGOL 60 source syntax
    @test -f engine/src/sixty.alg && echo "✓ Engine source exists" || (echo "✗ Engine source missing" && exit 1)
    @# Check for required SPDX headers
    @grep -q "SPDX-License-Identifier" engine/src/sixty.alg && echo "✓ SPDX header present" || echo "⚠ SPDX header missing"
    @# Validate output if built
    @test -f {{output_dir}}/index.html && echo "✓ Build output exists" || echo "⚠ Build output not found (run 'just build' first)"
    @echo "60-ssg: Tests complete"

# Check code formatting and style
fmt:
    @echo "60-ssg: Checking ALGOL 60 source formatting..."
    @# ALGOL 60 uses begin/end blocks - verify balanced blocks
    @echo "Checking block structure in engine/src/sixty.alg..."
    @begin_count=$$(grep -c "^begin\|[^a-z]begin" engine/src/sixty.alg || echo 0) && \
     end_count=$$(grep -c "^end\|[^a-z]end" engine/src/sixty.alg || echo 0) && \
     echo "  begin blocks: $$begin_count" && \
     echo "  end blocks: $$end_count"
    @echo "60-ssg: Format check complete"

# Lint code for policy compliance
lint:
    @echo "60-ssg: Running policy checks..."
    @# Check language policy
    @deno run --allow-read scripts/check-language-policy.js 2>/dev/null || node scripts/check-language-policy.js 2>/dev/null || echo "⚠ Language policy check requires Deno or Node"
    @# Check for banned file types
    @echo "Checking for banned file types..."
    @! find . -name "*.ts" -o -name "*.tsx" -o -name "*.go" -o -name "*.py" 2>/dev/null | grep -v node_modules | grep -v .git | grep . && echo "✓ No banned file types found" || true
    @echo "60-ssg: Lint complete"

# Clean build artifacts
clean:
    @echo "60-ssg: Cleaning build artifacts..."
    @rm -rf {{output_dir}}
    @echo "60-ssg: Removed {{output_dir}}/"
    @echo "60-ssg: Clean complete"

# Setup development environment
setup:
    @echo "60-ssg: Setting up development environment..."
    @echo "60-ssg: Checking for ALGOL 60 interpreter..."
    @which marst >/dev/null 2>&1 && echo "✓ MARST (ALGOL 60 to C) found" || echo "⚠ MARST not found - install via package manager"
    @which a60 >/dev/null 2>&1 && echo "✓ a60 interpreter found" || echo "⚠ a60 not found"
    @echo "60-ssg: Setup complete"

# Validate all machine-readable files
validate:
    @echo "60-ssg: Validating machine-readable files..."
    @for f in .machine_readable/*.scm; do \
        echo "Checking $$f..."; \
        grep -q "SPDX-License-Identifier" "$$f" && echo "  ✓ SPDX header" || echo "  ✗ Missing SPDX header"; \
    done
    @echo "60-ssg: Validation complete"
