module H = Html

type program = Adapter.program

let layout = (~siteTitle: string, ~baseUrl: string, ~title: string, ~body: string) => {
  let cssHref = baseUrl ++ (baseUrl == "/" ? "" : "") ++ "assets/site.css"
  `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>${H.escape(siteTitle)} — ${H.escape(title)}</title>
  <link rel="stylesheet" href="${cssHref}" />
</head>
<body>
  <div class="container">
    ${body}
    <div class="footer">Generated by befunge-ssg (Deno + ReScript). Static. Boring. Deployable.</div>
  </div>
</body>
</html>`
}

let renderTags = (tags: array<string>) =>
  tags
  ->Belt.Array.map(t => `<span class="tag">${H.escape(t)}</span>`)
  ->Belt.Array.joinWith("")

let renderIndexPage = (siteTitle: string, baseUrl: string, programs: array<program>) => {
  let cards =
    programs
    ->Belt.Array.map(p => {
      let href = `${baseUrl}programs/${H.escape(p.slug)}/`
      `<div class="card">
        <div class="h1"><a href="${href}">${H.escape(p.title)}</a></div>
        <div class="muted">${H.escape(p.summary)}</div>
        <div style="margin-top:10px">${renderTags(p.tags)}</div>
        <div class="kv">
          <div>grid: ${Int.toString(p.width)}×${Int.toString(p.height)}</div>
          <div>file: ${H.escape(p.filename)}</div>
        </div>
      </div>`
    })
    ->Belt.Array.joinWith("")

  layout(
    ~siteTitle,
    ~baseUrl,
    ~title="Index",
    ~body=
      `<div class="header">
        <div>
          <div class="h1">${H.escape(siteTitle)}</div>
          <div class="muted">A small gallery of Befunge programs rendered as 2D grids.</div>
        </div>
        <div class="muted"><a href="https://esolangs.org/wiki/Befunge">Befunge</a></div>
      </div>
      <div class="grid">${cards}</div>`,
  )
}

let renderProgramPage = (siteTitle: string, baseUrl: string, p: program) => {
  let back = `${baseUrl}`
  let grid = H.escape(p.rawCode)

  layout(
    ~siteTitle,
    ~baseUrl,
    ~title=p.title,
    ~body=
      `<div class="header">
        <div>
          <div class="h1">${H.escape(p.title)}</div>
          <div class="muted">${H.escape(p.summary)}</div>
          <div style="margin-top:10px">${renderTags(p.tags)}</div>
        </div>
        <div class="muted"><a href="${back}">← index</a></div>
      </div>

      <div class="kv">
        <div>grid: ${Int.toString(p.width)}×${Int.toString(p.height)}</div>
        <div>file: ${H.escape(p.filename)}</div>
        <div>slug: ${H.escape(p.slug)}</div>
      </div>

      <h2 style="margin-top:18px; font-size:14px; color:#cfcfcf;">Grid</h2>
      <div class="pre"><pre>${grid}</pre></div>`,
  )
}
