#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2025 hyperpolymath
#
# chicxulub-ssg: Bash static site generator
# "Extinction-level site generation" - pure shell implementation
# Named after the asteroid impact that ended the dinosaurs

set -euo pipefail

# Configuration
SITE_NAME="${SITE_NAME:-chicxulub-site}"
OUTPUT_DIR="${OUTPUT_DIR:-_site}"

# ANSI colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Print status message
log_info() {
    echo -e "${GREEN}chicxulub-ssg:${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}chicxulub-ssg:${NC} $1"
}

log_error() {
    echo -e "${RED}chicxulub-ssg:${NC} $1" >&2
}

# Escape HTML special characters
# Usage: escape_html "string"
escape_html() {
    local text="$1"
    text="${text//&/&amp;}"
    text="${text//</&lt;}"
    text="${text//>/&gt;}"
    text="${text//\"/&quot;}"
    text="${text//\'/&#39;}"
    echo "$text"
}

# Parse simple Markdown to HTML
# Usage: parse_markdown "markdown_content"
parse_markdown() {
    local markdown="$1"
    local html=""

    while IFS= read -r line || [[ -n "$line" ]]; do
        if [[ "$line" =~ ^#\ (.+)$ ]]; then
            html+="<h1>${BASH_REMATCH[1]}</h1>"$'\n'
        elif [[ "$line" =~ ^##\ (.+)$ ]]; then
            html+="<h2>${BASH_REMATCH[1]}</h2>"$'\n'
        elif [[ "$line" =~ ^###\ (.+)$ ]]; then
            html+="<h3>${BASH_REMATCH[1]}</h3>"$'\n'
        elif [[ "$line" =~ ^[-*]\ (.+)$ ]]; then
            html+="<li>${BASH_REMATCH[1]}</li>"$'\n'
        elif [[ -n "$line" ]]; then
            html+="<p>$line</p>"$'\n'
        fi
    done <<< "$markdown"

    echo "$html"
}

# Render page to HTML
# Usage: render_page "title" "content"
render_page() {
    local title="$1"
    local content="$2"
    local escaped_title
    escaped_title=$(escape_html "$title")

    cat <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${escaped_title}</title>
    <meta name="generator" content="chicxulub-ssg">
</head>
<body>
    <article>
        <h1>${escaped_title}</h1>
        ${content}
    </article>
    <footer>
        <p>Generated by chicxulub-ssg - extinction-level static sites</p>
    </footer>
</body>
</html>
EOF
}

# Build a single page
# Usage: build_page "title" "path" "content"
build_page() {
    local title="$1"
    local path="$2"
    local content="$3"
    local out_path="${OUTPUT_DIR}/${path}.html"

    # Create parent directories if needed
    mkdir -p "$(dirname "$out_path")"

    # Render and write
    render_page "$title" "$content" > "$out_path"
    log_info "Built ${out_path}"
}

# Build site from content directory
# Usage: build_site [content_dir]
build_site() {
    local content_dir="${1:-content}"
    local page_count=0

    log_info "Impact initiated for site '${SITE_NAME}'..."

    # Create output directory
    mkdir -p "$OUTPUT_DIR"

    # Check if content directory exists
    if [[ -d "$content_dir" ]]; then
        # Process Markdown files
        while IFS= read -r -d '' file; do
            local basename
            basename=$(basename "$file" .md)
            local relative_path
            relative_path=$(dirname "${file#$content_dir/}")

            # Extract title from first # heading or filename
            local title
            title=$(grep -m1 '^# ' "$file" 2>/dev/null | sed 's/^# //' || echo "$basename")

            # Parse content
            local content
            content=$(parse_markdown "$(cat "$file")")

            # Build output path
            local out_path
            if [[ "$relative_path" == "." ]]; then
                out_path="$basename"
            else
                out_path="${relative_path}/${basename}"
            fi

            build_page "$title" "$out_path" "$content"
            ((page_count++))
        done < <(find "$content_dir" -name '*.md' -print0 2>/dev/null)
    fi

    # If no content found, build example page
    if [[ $page_count -eq 0 ]]; then
        log_warn "No content found, creating example page..."
        build_page "Welcome" "index" "<p>Welcome to chicxulub-ssg!</p><p>Extinction-level static site generation.</p>"
        ((page_count++))
    fi

    log_info "Impact complete: ${page_count} pages generated"
    log_info "Output directory: ${OUTPUT_DIR}"
}

# Clean output directory
clean() {
    if [[ -d "$OUTPUT_DIR" ]]; then
        rm -rf "$OUTPUT_DIR"
        log_info "Cleaned ${OUTPUT_DIR}"
    fi
}

# Show usage
usage() {
    cat <<EOF
chicxulub-ssg - Extinction-level static site generation

Usage: $(basename "$0") [command] [options]

Commands:
    build [content_dir]   Build site from content directory (default: content)
    clean                 Remove output directory
    help                  Show this help message

Environment Variables:
    SITE_NAME    Site name (default: chicxulub-site)
    OUTPUT_DIR   Output directory (default: _site)

Examples:
    $(basename "$0") build
    $(basename "$0") build ./pages
    SITE_NAME="My Site" $(basename "$0") build
EOF
}

# Main entry point
main() {
    local command="${1:-build}"

    case "$command" in
        build)
            shift || true
            build_site "${1:-content}"
            ;;
        clean)
            clean
            ;;
        help|--help|-h)
            usage
            ;;
        *)
            log_error "Unknown command: $command"
            usage
            exit 1
            ;;
    esac
}

# Run main if not sourced
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
