c SPDX-License-Identifier: AGPL-3.0-or-later
c SPDX-FileCopyrightText: 2025 hyperpolymath
c
c rats-ssg - Ratfor Static Site Generator
c "Let rationals flow. Let fortrans compute. Let sites compile."
c
c Ratfor is a preprocessor for Fortran that provides C-like syntax.
c Compile with: ratfor rats.r > rats.f && gfortran rats.f -o rats
c Run with: ./rats build | init | clean

c ============================================================================
c Configuration
c ============================================================================

      define(MAXLINE, 1024)
      define(MAXBUF, 32000)

c ============================================================================
c Main Program
c ============================================================================

      program rats
      character*20 cmd
      integer nargs

      nargs = iargc()
      if (nargs .ge. 1) {
          call getarg(1, cmd)
          if (cmd .eq. 'build') {
              call build
          } else if (cmd .eq. 'init') {
              call init
          } else if (cmd .eq. 'clean') {
              call clean
          } else {
              call help
          }
      } else {
          call help
      }

      stop
      end

c ============================================================================
c Build Command
c ============================================================================

      subroutine build
      character*256 srcpath, outpath
      integer ierr

      write(*,*) 'rats-ssg: Building site...'
      write(*,*) '  Output directory: _site'

c     Create output directory
      call system('mkdir -p _site')

c     Process index.md
      srcpath = 'content/index.md'
      outpath = '_site/index.html'

      call process(srcpath, outpath, ierr)

      if (ierr .eq. 0) {
          write(*,*) 'rats-ssg: Build complete.'
      } else {
          write(*,*) 'rats-ssg: Build failed.'
      }

      return
      end

c ============================================================================
c Process File
c ============================================================================

      subroutine process(srcpath, outpath, ierr)
      character*(*) srcpath, outpath
      integer ierr
      character*MAXLINE lines(1000)
      character*256 title, date
      logical draft
      integer nlines, bodystart, i
      integer inunit, outunit

      write(*,*) '  Processing: ', trim(srcpath)

      inunit = 10
      outunit = 11
      ierr = 0

c     Read input file
      open(unit=inunit, file=srcpath, status='old', iostat=ierr)
      if (ierr .ne. 0) {
          write(*,*) '  Error: Cannot open ', trim(srcpath)
          return
      }

      nlines = 0
      do while (.true.)
          nlines = nlines + 1
          read(inunit, '(A)', end=100) lines(nlines)
      end do
100   continue
      nlines = nlines - 1
      close(inunit)

c     Parse frontmatter
      call parsefm(lines, nlines, title, date, draft, bodystart)

      if (draft) {
          write(*,*) '    Skipping draft'
          return
      }

c     Write output
      open(unit=outunit, file=outpath, status='replace', iostat=ierr)
      if (ierr .ne. 0) {
          write(*,*) '  Error: Cannot create ', trim(outpath)
          return
      }

c     HTML header
      write(outunit, '(A)') '<!DOCTYPE html>'
      write(outunit, '(A)') '<html lang="en">'
      write(outunit, '(A)') '<head>'
      write(outunit, '(A)') '<meta charset="UTF-8">'
      write(outunit, '(A,A,A)') '<title>', trim(title), ' | Rats Site</title>'
      write(outunit, '(A)') '<style>'
      write(outunit, '(A)') 'body{font-family:monospace;max-width:70ch;'
      write(outunit, '(A)') 'margin:0 auto;padding:2rem;}'
      write(outunit, '(A)') 'pre{background:#f5f5f5;padding:1rem;}'
      write(outunit, '(A)') '</style>'
      write(outunit, '(A)') '</head>'
      write(outunit, '(A)') '<body>'
      write(outunit, '(A)') '<article>'
      write(outunit, '(A,A,A)') '<h1>', trim(title), '</h1>'

      if (len_trim(date) .gt. 0) {
          write(outunit, '(A,A,A)') '<time>', trim(date), '</time>'
      }

c     Parse markdown content
      call parsemd(lines, nlines, bodystart, outunit)

c     HTML footer
      write(outunit, '(A)') '</article>'
      write(outunit, '(A)') '<footer><p>Generated by rats-ssg (Ratfor)</p></footer>'
      write(outunit, '(A)') '</body>'
      write(outunit, '(A)') '</html>'

      close(outunit)
      write(*,*) '  Written: ', trim(outpath)

      return
      end

c ============================================================================
c Parse Frontmatter
c ============================================================================

      subroutine parsefm(lines, nlines, title, date, draft, bodystart)
      character*(*) lines(*)
      integer nlines
      character*(*) title, date
      logical draft
      integer bodystart
      character*MAXLINE line, key, value
      integer i, colonpos

      title = 'Untitled'
      date = ''
      draft = .false.
      bodystart = 1

      if (nlines .eq. 0) return
      if (trim(lines(1)) .ne. '---') return

      do i = 2, nlines
          line = trim(lines(i))
          if (line .eq. '---') {
              bodystart = i + 1
              return
          }

          colonpos = index(line, ':')
          if (colonpos .gt. 0) {
              key = trim(line(1:colonpos-1))
              value = trim(line(colonpos+1:))

              if (key .eq. 'title') {
                  title = value
              } else if (key .eq. 'date') {
                  date = value
              } else if (key .eq. 'draft') {
                  draft = (value .eq. 'true') .or. (value .eq. 'yes')
              }
          }
      end do

      return
      end

c ============================================================================
c Parse Markdown
c ============================================================================

      subroutine parsemd(lines, nlines, start, outunit)
      character*(*) lines(*)
      integer nlines, start, outunit
      character*MAXLINE line, trimmed
      logical incode
      integer i

      incode = .false.

      do i = start, nlines
          line = lines(i)
          trimmed = trim(line)

c         Code blocks
          if (trimmed(1:3) .eq. '```') {
              if (incode) {
                  write(outunit, '(A)') '</code></pre>'
                  incode = .false.
              } else {
                  write(outunit, '(A)') '<pre><code>'
                  incode = .true.
              }
          } else if (incode) {
              write(outunit, '(A)') trim(line)
c         Headers
          } else if (trimmed(1:4) .eq. '### ') {
              write(outunit, '(A,A,A)') '<h3>', trim(trimmed(5:)), '</h3>'
          } else if (trimmed(1:3) .eq. '## ') {
              write(outunit, '(A,A,A)') '<h2>', trim(trimmed(4:)), '</h2>'
          } else if (trimmed(1:2) .eq. '# ') {
              write(outunit, '(A,A,A)') '<h1>', trim(trimmed(3:)), '</h1>'
c         List items
          } else if (trimmed(1:2) .eq. '- ' .or. trimmed(1:2) .eq. '* ') {
              write(outunit, '(A,A,A)') '<li>', trim(trimmed(3:)), '</li>'
c         Paragraph
          } else if (len_trim(trimmed) .gt. 0) {
              write(outunit, '(A,A,A)') '<p>', trim(trimmed), '</p>'
          }
      end do

      return
      end

c ============================================================================
c Init Command
c ============================================================================

      subroutine init
      integer outunit, ierr

      write(*,*) 'rats-ssg: Initializing new site...'

      call system('mkdir -p content')
      call system('mkdir -p _site')

      outunit = 10
      open(unit=outunit, file='content/index.md', status='replace',
     +     iostat=ierr)

      write(outunit, '(A)') '---'
      write(outunit, '(A)') 'title: Welcome to Rats'
      write(outunit, '(A)') 'date: 2025-01-18'
      write(outunit, '(A)') '---'
      write(outunit, '(A)') ''
      write(outunit, '(A)') '# Welcome'
      write(outunit, '(A)') ''
      write(outunit, '(A)') 'This site was built with **rats-ssg**,'
      write(outunit, '(A)') 'a Ratfor-powered SSG.'
      write(outunit, '(A)') ''
      write(outunit, '(A)') '## Ratfor Features'
      write(outunit, '(A)') ''
      write(outunit, '(A)') '- C-like syntax for Fortran'
      write(outunit, '(A)') '- Structured programming'
      write(outunit, '(A)') '- Historical significance'
      write(outunit, '(A)') '- Preprocessor approach'

      close(outunit)

      write(*,*) '  Created sample content'
      write(*,*) 'rats-ssg: Site initialized.'
      write(*,*) 'Run ''./rats build'' to build.'

      return
      end

c ============================================================================
c Clean Command
c ============================================================================

      subroutine clean

      write(*,*) 'rats-ssg: Cleaning _site/...'
      call system('rm -rf _site')
      write(*,*) 'rats-ssg: Clean complete.'

      return
      end

c ============================================================================
c Help Command
c ============================================================================

      subroutine help

      write(*,*) 'rats-ssg - Ratfor Static Site Generator'
      write(*,*) ''
      write(*,*) 'USAGE:'
      write(*,*) '  rats <command>'
      write(*,*) ''
      write(*,*) 'COMMANDS:'
      write(*,*) '  build    Build the site'
      write(*,*) '  init     Initialize a new site'
      write(*,*) '  clean    Remove generated files'
      write(*,*) '  help     Show this help'
      write(*,*) ''
      write(*,*) 'FEATURES:'
      write(*,*) '  - Ratfor preprocessed Fortran'
      write(*,*) '  - Structured control flow'
      write(*,*) '  - Historical computing tribute'

      return
      end
